# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-22.9"

conda:
  environment: environment.yaml

sphinx:
  configuration: docs/conf.py
  # disable this for more lenient docs builds
  # fail_on_warning: true
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
