[build-system]
requires = ["uv_build >= 0.5.0, <0.12.0"]
build-backend = "uv_build"

[project]
name = "sparrow"
version = "0.0.1"
description = "Napari plugin for spatial transcriptomics data analysis"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [
    { name = "dambi" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: napari",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Testing",
]
requires-python = ">=3.11"
dependencies = [
    "setuptools>=42.0.0,<=80.10.2",
    "spatialdata==0.4.0",
    "numpy<2",
    "distributed",
    "spatialdata-io>=0.6.0",
    "scanpy>=1.9.1",
    "voronoi-diagram-for-polygons>=0.1.6",
    "rasterio>=1.3.2",
    "seaborn>=0.12.2",
    "leidenalg>=0.9.1",
    "geopandas>=1.0.1",
    "omegaconf==2.3.0",
    "pyarrow<=21.0.0",  # latest pyarrow breaks spatialdata: https://github.com/scverse/spatialdata/issues/1000
    "nptyping",
    "magicgui",
    "pyrootutils",
    "universal_pathlib",
    "datasets",
    "crick",
]

[project.urls]
"Bug Tracker" = "https://github.com/saeyslab/napari-sparrow/issues"
"Documentation" = "https://github.com/saeyslab/napari-sparrow#README.md"
"Source Code" = "https://github.com/saeyslab/napari-sparrow"
"User Support" = "https://github.com/saeyslab/napari-sparrow/issues"

[project.optional-dependencies]
plugin = [
    "napari[all]>=0.4.18",
    "hydra-core>=1.2.0",
    "hydra-colorlog>=1.2.0",
    "napari-spatialdata>=0.2.6",
    "cellpose>=2.2.3,<4.0",
    "pytest-qt",
]
testing = [
    "hydra-core>=1.2.0",
    "hydra-colorlog>=1.2.0",
    "cellpose>=2.2.3,<4.0",
    "datasets",
    "jax>=0.4.6,<=0.4.23",
    "jaxlib>=0.4.6,<=0.4.23",
    "basicpy==1.0.0",
    "opencv-python",
    "pytest",
    "pytest-cov",
    "tox",
    "nbconvert",
]
notebooks = [
    "ipykernel>=6.29",
    "jupyter>=1.0.0",
    "notebook>=7.0.0",
    "nbformat>=5.10.0",
    "nbconvert>=7.0.0",
    "ipython>=8.6.0",
]
tiling = [
    "jax>=0.4.6,<=0.4.23",
    "jaxlib>=0.4.6,<=0.4.23",
    "basicpy==1.0.0",
]
cli = [
    "hydra-core>=1.2.0",
    "hydra-colorlog>=1.2.0",
    "submitit>=1.4.5",
    "hydra-submitit-launcher>=1.2.0",
]
docs = [
    "sphinx>=4.5",
    "sphinx-book-theme>=1.0.0",
    "sphinx_rtd_theme",
    "myst-nb",
    "sphinxcontrib-bibtex>=1.0.0",
    "sphinx-autodoc-typehints",
    "sphinx-design",
    "ipython>=8.6.0",
    "sphinx-copybutton",
]

[project.scripts]
sparrow = "sparrow.single:main"

[project.entry-points."napari.manifest"]
sparrow = "sparrow:napari.yaml"

[tool.uv.build-backend]
source-dir = "src"

[tool.coverage.run]
omit = ["src/sparrow/_tests/*", "experiments/*", "src/sparrow/widgets/*" ]

[tool.ruff]
src = ["src"]
line-length = 120
select = [
    "F",  # Errors detected by Pyflakes
    "E",  # Error detected by Pycodestyle
    "W",  # Warning detected by Pycodestyle
    "I",  # isort
    "D",  # pydocstyle
    "B",  # flake8-bugbear
    "TID",  # flake8-tidy-imports
    "C4",  # flake8-comprehensions
    "BLE",  # flake8-blind-except
    "UP",  # pyupgrade
    "RUF100",  # Report unused noqa directives
]
ignore = [
    # line too long -> we accept long comment lines; formatter gets rid of long code lines
    "E501",
    # Do not assign a lambda expression, use a def -> lambda expression assignments are convenient
    "E731",
    # allow I, O, l as variable names -> I is the identity matrix
    "E741",
    # Missing docstring in public package
    "D104",
    # Missing docstring in public module
    "D100",
    # Missing docstring in __init__
    "D107",
    # Errors from function calls in argument defaults. These are fine when the result is immutable.
    "B008",
    # __magic__ methods are are often self-explanatory, allow missing docstrings
    "D105",
    # first line should end with a period [Bug: doesn't work with single-line docstrings]
    "D400",
    # First line should be in imperative mood; try rephrasing
    "D401",
    ## Disable one in each pair of mutually incompatible rules
    # We don’t want a blank line before a class docstring
    "D203",
    # We want docstrings to start immediately after the opening triple quote
    "D213",
]
extend-include = ["*.ipynb"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.ruff.per-file-ignores]
"docs/*" = ["I"]
"**/_tests/*" = ["D"]
"*/__init__.py" = ["F401"]
"**/test_data/*" = ["ALL"]


[tool.pytest.ini_options]
testpaths = ['src/sparrow/_tests']
