# @package segmentation

defaults:
  - cellpose

flow_threshold: 0.85
diameter: 100
cellprob_threshold: -4
model_type: "cyto"
channels: [2, 1] # use [2,1] if you want to segment polyt + nucleus on DAPI; [2,0] if you only want to use polyt
chunks: 2048
crop_param: [49000, 53000, 53000, 57000] # for debugging
small_size_vis: [49000, 53000, 53000, 57000] # null
