# @package segmentation

defaults:
- default

min_size: 80
flow_threshold: 0.8
diameter:  50
cellprob_threshold: -2
model_type: "nuclei"
channels: [0, 0]
do_3D: False
anisotropy: null # should be specified if do_3D is set to True.
