defaults:
  - default

# In liver, the marker genes for hepatocytes are everywhere, but way higher expressed in hepatocytes. This result in a high score for hepatocytes in cells that aren't hepatocytes.
# Therefore, if Hepatcytes score for a cell is lower than 5.6 ( i.e. not above threshold for being considered Hepatocyte, we divide by 7.0).
#marker_genes:
#  Hepatocytes: [5.6, 7.0]

# celltype_indexes groups all cell types together with index in this list. Note that index is the index after alphabetically sorting the cell types (via np.sort)
# probably wiser to adapt the marker.csv file before starting the analyses
celltype_indexes:
  Other_ImmuneCells: [1, 2, 8, 14, 15, 16, 17, 18, 19, 21, 22, 26]
  fibroblast: [4, 5, 23, 25]
  stellate: [28, 29, 30]

colors:
  [
    "#914d22",
    "#c61b84",
    "#ec67a7",
    "#edabcb",
    "#5da6db",
    "#8f4716",
    "#fa8307",
    "#b0763a",
    "#d0110b",
    "#f62c4f",
    "#fed8b1",
    "#cc7722",
    "#929591",
    "#E45466",
    "#a31a2a",
  ]
